"""empty message

Revision ID: 930579172c04
Revises: ce91e59cdc99
Create Date: 2023-06-24 21:59:24.421760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930579172c04'
down_revision = 'ce91e59cdc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
